favorite_stream/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include
from django.views.generic.base import RedirectView


from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('oauth_login.urls')),
    url(r'^stream/', include('stream.urls')),
    url(r'^$', RedirectView.as_view(url='auth/login/'), name='home')
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + urlpatterns

handler404 = 'favorite_stream.views.error_404'

oauth_login/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib.auth import views as helper_views
from . import views

app_name = 'oauth_login'
urlpatterns = [
    url(r'^login/$', helper_views.login,
        {'template_name': 'oauth_login/login.html'},
        name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

stream/urls.py
from django.conf.urls import url

from . import views

app_name = 'stream'

urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^watch/', views.Watch.as_view(), name='watch'),
]

oauth_login/models.py
# from django.db import models

# Create your models here.

stream/models.py
# from django.db import models
#
# from django.contrib.auth.models import User
#
# class FavoriteStreamer(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     streamer_nickname = models.CharField(max_length=200, db_index=True, unique=True)
#
#     def __str__(self):
#         return f'Favorite Streamer: {self.streamer_nickname}'

favorite_stream/views.py
from django.shortcuts import render


def error_404(request):
    return render(request, '404.html', status=404)

oauth_login/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from social_core.exceptions import AuthUnknownError


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        try:
            twitch_login = user.social_auth.get(provider='twitch')
            # print(twitch_login.extra_data)
            twitch_login.disconnect(twitch_login)
        except AuthUnknownError:
            print('No social user associated with the user')
        logout(request)
        return redirect('oauth_login:login')

stream/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.conf import settings

import json

from .helpers import TwitchAPI
from . import error_messages


@method_decorator(login_required, name='dispatch')
class Dashboard(View):
    template_name = 'stream/dashboard.html'

    def get(self, request):
        twitch_api = TwitchAPI(request)
        # twitch_api.refresh_token()
        twitch_username = twitch_api.get_twitch_username()
        context = {
            'twitch_username': twitch_username
        }
        return render(request, self.template_name, context)

    def render_page_with_error(self, request, error_message, status_code=200):
        return render(request, self.template_name, {
            'error_message': error_message,
        }, status=status_code)

    def render_get_streamer_error(self, request, streamer_req):
        error_req = json.loads(streamer_req.text)
        error_message = f"Code: {error_req.get('status')} | {error_req.get('error')}"
        if error_req.get('message'):
            error_message += f": {error_req.get('message')}"
        return self.render_page_with_error(request, error_message, error_req.get('status'))

    def post(self, request):
        streamer_name = request.POST['streamer_name']
        twitch_api = TwitchAPI(request)

        streamer_req = twitch_api.get_streamer_req(streamer_name)
        if streamer_req.status_code == 401:
            # Refresh token if requisition is denied as explained in
            # https://dev.twitch.tv/docs/authentication/#refresh-in-response-to-server-rejection-for-bad-authentication
            twitch_api.refresh_token()
            streamer_req = twitch_api.get_streamer_req(streamer_name)
        elif streamer_req.status_code != 200:
            return self.render_get_streamer_error(request, streamer_req)

        streamer_data = json.loads(streamer_req.text)['data']
        if not streamer_data:
            error_message = error_messages.INVALID_TWITCH_USERNAME
            return self.render_page_with_error(request, error_message)

        streamer_data = streamer_data[0]
        data = {'streamer_data': streamer_data}
        request.session['data'] = data

        return HttpResponseRedirect(reverse('stream:watch'))


@method_decorator(login_required, name='dispatch')
class Watch(View):
    template_name = 'stream/watch.html'

    @staticmethod
    def generate_session_data(streamer_data, twitch_api):
        data = {
            'streamer_data': streamer_data,
            'can_pub_sub': streamer_data.get('id') == twitch_api.get_user_id(),
            'api_data': {
                'client_key': settings.SOCIAL_AUTH_TWITCH_KEY,
                'events_url': settings.GET_EVENTS_API_TEMP.substitute(id=streamer_data.get('id'))
            }
        }
        # Passes necessary info to use pub_sub
        if data.get('can_pub_sub'):
            api_data_comp = {
                'access_token': twitch_api.get_access_token(),
                # 'expiration': twitch_api.get_expiration_time(),
                # 'refresh_token': twitch_api.get_refresh_token(),
                'ws_url': settings.TWITCH_WS_URL
            }
            data.get('api_data').update(api_data_comp)
        return data

    def get(self, request):
        data = request.session.get('data')
        if not data:
            return HttpResponseRedirect(reverse('stream:dashboard'))
        streamer_name = data.get('streamer_data').get('login')
        twitch_api = TwitchAPI(request)
        streamer_data = data.get('streamer_data')
        context = {
            'streamer_embed_url': settings.EMBED_PLAYER_URL_TEMP.substitute(streamer_name=streamer_name),
            'streamer_chat_url': settings.EMBED_CHAT_URL_TEMP.substitute(streamer_name=streamer_name),
            'can_pub_sub': streamer_data.get('id') == twitch_api.get_user_id(),
            'context_data': json.dumps(self.generate_session_data(
                streamer_data,
                twitch_api)
            )
        }
        return render(request, self.template_name, context=context)

favorite_stream/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Favorite Streamer</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA"
    crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block app_style %}

  {% endblock app_style %}

</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" style="" href="{% url 'home' %}">
        <img src="{% static '/img/0_twitch_logo.png' %}" alt="Twitch Logo"> <span> Favorite Streamer</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'stream:dashboard' %}">Dashboard
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'oauth_login:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>


  </nav>

  {% if error_message %}

  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
    <strong>Error:</strong> {{ error_message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}

  {% block content %}
  {% endblock content %}

  <footer id="footer-main">
    <div class="container">
      <div class="row">
        <p>Coded by <a href="https://www.linkedin.com/in/diego-lelis/" target="_blank">Diego Lelis</a></p>
      </div>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp"
    crossorigin="anonymous"></script>

  {% block app_js %}
  {% endblock app_js %}

</body>

</html>

oauth_login/templates/exp/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible">
    <title>FStream</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    
</body>
</html>

oauth_login/templates/oauth_login/login.html
{% extends 'layout.html' %}
{% load static %}

{% block app_style %}

<link rel="stylesheet" href="{% static 'oauth_login/css/style.css' %}">
{% endblock %}
{% block content %}
<div section="content" id="content">
    <section id="login", class="login-area">
        <div class="section-content">
            <div class="container">
                <div class="col-md-6">
                    <div class="login-text">
                        <h3>Aboout this application</h3>
                        <p class="lead">This application was developed using mainly Django, Bootstrap and JavaScript.</p>
                        <p>
                        </p>
                        {% if not user.is_authenticated %}
                        <h5>Connect with Twitch to Start</h5>

                        <form method="post" action="{% url 'oauth_login:social:begin' 'twitch' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-block btn-lg btn-info">Connect with Twitch</button>
                        </form>
                        {% else %}
                        <h5>You are already logged</h5>
                        <form method="get" action="{% url 'stream:dashboard' %}">
                            <button type="submit" class="btn btn-block btn-lg btn-info">Go to My Dashboard</button>
                        </form>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

stream/templates/stream/dashboard.html
{% extends 'layout.html' %}

{% block content %}
  <div section="content" id="content">
    <div section="dashboard" id="dashboard">
      <div id="user-info" class="mt-3">
        <div class="row">
          <div class="container text-center">
            {% comment %} <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
              alt="User image" width="50"> {% endcomment %}
            <p>Welcome <strong>{{ twitch_username }}</strong></p>
            <p>Enter your favorite Twitch streamer name to begin.</p>
          </div>
        </div>
      </div>

      <hr>
      <div id="new-favorite-streamer-form">
        <div class="row">
          <div class="container text-center">
            <form class="form-inline justify-content-center align-items-center" action="{% url 'stream:dashboard' %}" method="post">
              {% csrf_token %}
              <label class="sr-only">Username</label>
              <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                  <div class="input-group-text">@</div>
                </div>
                <input required type="text" class="form-control" id="streamer_name" name="streamer_name" placeholder="Twitch streamer name">
              </div>
              <button type="submit" class="btn btn-primary mb-2" value="Vote">Set</button>
            </form>

          </div>
        </div>
      </div>
    </div>
    <hr>

    <!-- <div id="favorite-streamer-list" class="mt-3 mb-3">
    <div class="row">
      <div class="container text-center">
        Favorite Streamer List
      </div>
    </div>
  </div> -->


  </div>

{% endblock %}

stream/templates/stream/watch.html
{% extends 'layout.html' %} {% load static %} {% block app_style %}

<link rel="stylesheet" href="{% static 'stream/css/style.css' %}" />

{% endblock %} {% block content %}

<div section="content" id="content">
  <div section="favorite-streamer" id="favorite-streamer">
    <ul class="nav nav-tabs justify-content-center align-items-center mt-2" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="streamer-tab" data-toggle="tab" href="#streamer" role="tab" aria-controls="streamer"
          aria-selected="true">Streamer</a>
      </li>
      {% if can_pub_sub %}
      <li class="nav-item">
        <a class="nav-link" id="last-activity-tab" data-toggle="tab" href="#last-activity" role="tab"
          aria-controls="last-activity" aria-selected="false">Last Chat Events</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" id="events-tab" data-toggle="tab" href="#events" role="tab" aria-controls="events"
          aria-selected="false">Next Events</a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane show active fade justify-content-center align-items-center text-center" id="streamer" role="tabpanel"
        aria-labelledby="streamer-tab">
        <div class="row">
           <div class="col-md-9 stream-col">
            <div class="stream-iframe-container">
              <iframe id="stream" src={{ streamer_embed_url }}
                frameborder="
                0" scrolling="no" allowfullscreen="true">
              </iframe>
            </div>
          </div>

          <div class="col-md-3 chat-col">
            <div class="chat-iframe-container">
              <iframe id="chat" frameborder="0" height="500" width="100%" scrolling="no" id="chat_embed" src={{ streamer_chat_url }}
              >
              </iframe>
            </div>
          </div> 
        </div> 
      </div>
      {% if can_pub_sub %}
      <div
        class="
                tab-pane fade justify-content-center align-items-center text-center" id="last-activity"
                role="tabpanel" aria-labelledby="last-activity-tab">
        <div class="container col-md-6 text-left">
          <ul class="list-group list-group-flush" id="activity-list">
            <li class="list-group-item">
            <li class="list-group-item" item-id="start">Awaiting for the first activity...</li>
          </ul>
        </div>
      </div>
      {% endif %}

            <div class="tab-pane fade justify-content-center align-items-center text-center" id="events" role="tabpanel"
              aria-labelledby="events-tab">
              <div class="container col-md-6 text-left">
                <ul class="list-group" id="event-list">
                  <li item-id='start' class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 text-right">
                      {% comment %} <small class="text-muted text-right">28 Feb</small> {% endcomment %}
                    </div>
                    <p class="mb-1">Fetching events...</p>
                    {% comment %} <small class="text-muted">Desc.</small> {% endcomment %}
                  </li>
                  {% comment %} <li class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 text-right">
                      <small class="text-muted text-right">28 Feb</small>
                    </div>
                    <p class="mb-1">Title.</p>
                    <small class="text-muted">Desc.</small>
                  </li> {% endcomment %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      

      {% endblock %} 
      
      {% block app_js %}
      <script>
        var contextData = JSON.parse(`{{ context_data|safe }}`);
        var STARTMESSAGEHASH = "start";
        var currentActivMsg = new Set([STARTMESSAGEHASH]);
        var currentEvents = new Set([STARTMESSAGEHASH]);
        var DEBUG = false
        var TESTING = false
      </script>

      <script src="{% static "stream/js/last-activity.js" %}"></script>
      <script src="{% static "stream/js/websock.js" %}"></script>
      <script src="{% static "stream/js/events.js" %}"></script>
      <script src="{% static "stream/js/main.js" %}"></script>
      {% endblock %}